repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: f4d7745e17a28aad7eed2f4874ca8d1568c11c4c # v22.1.8
    hooks:
      - id: clang-format
        types_or: [file]
        files: \.(c|h|cpp|hpp|ipp|cu|cuh|sycl|hip)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
  - repo: local
    hooks:
      - id: cppcheck
        name: cppcheck
        entry: cppcheck --project=build/compile_commands.json --enable=all --cppcheck-build-dir=build --suppressions-list=cppcheck.suppressions -i "build/_deps/*" --error-exitcode=1 --check-level=exhaustive --inline-suppr
        types: [c++]
        language: system
        pass_filenames: false
      - id: clang-tidy
        name: clang-tidy
        entry: run-clang-tidy -p build/ -header-filter='.*'
        types: [c++]
        language: system
        exclude: (build|downstream)
  - repo: https://codeberg.org/fsfe/reuse-tool
    rev: a1bb792acda6fd0724936b4ebbdbc8eceb9c0459 # v6.2.0
    hooks:
      - id: reuse
  - repo: https://github.com/BlankSpruce/gersemi-pre-commit
    rev: b9d6d13dc9b753c5ff24ed5f8470671189c3fcf0 # 0.28.0
    hooks:
    - id: gersemi
      args: ["-i"]
