name: sanitizers

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sanitizers:
    name: Sanitizers (${{ matrix.preset }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        preset:
          - asan
          - ubsan
          #- tsan # disabled for now as couldn't silence false positives reliably
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang

      - name: Configure, build, test
        env:
          CC: clang
          CXX: clang++
        run: cmake --workflow --preset ${{ matrix.preset }}
